package com.manager.pojo;

import java.sql.Timestamp;
import java.util.Date;

/**
 * Database Table Remarks:
 *   内容分类
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_content_category
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class TbContentCategory {
    /**
     * Database Column Remarks:
     *   类目ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   父类目ID=0时，代表的是一级的类目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * Database Column Remarks:
     *   分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   状态。可选值:1(正常),2(删除)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   排列序号，表示同级类目的展现次序，如数值相等则按名称次序排列。取值范围:大于零的整数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.sort_order
     *
     * @mbggenerated
     */
    private Integer sortOrder;

    /**
     * Database Column Remarks:
     *   该类目是否为父类目，1为true，0为false
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.is_parent
     *
     * @mbggenerated
     */
    private Boolean isParent;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.created
     *
     * @mbggenerated
     */
    private Timestamp created;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_content_category.upTimestampd
     *
     * @mbggenerated
     */
    private Timestamp updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.id
     *
     * @return the value of tb_content_category.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.id
     *
     * @param id the value for tb_content_category.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.parent_id
     *
     * @return the value of tb_content_category.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.parent_id
     *
     * @param parentId the value for tb_content_category.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.name
     *
     * @return the value of tb_content_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.name
     *
     * @param name the value for tb_content_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.status
     *
     * @return the value of tb_content_category.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.status
     *
     * @param status the value for tb_content_category.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.sort_order
     *
     * @return the value of tb_content_category.sort_order
     *
     * @mbggenerated
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.sort_order
     *
     * @param sortOrder the value for tb_content_category.sort_order
     *
     * @mbggenerated
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.is_parent
     *
     * @return the value of tb_content_category.is_parent
     *
     * @mbggenerated
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.is_parent
     *
     * @param isParent the value for tb_content_category.is_parent
     *
     * @mbggenerated
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.created
     *
     * @return the value of tb_content_category.created
     *
     * @mbggenerated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.created
     *
     * @param created the value for tb_content_category.created
     *
     * @mbggenerated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_content_category.upTimestampd
     *
     * @return the value of tb_content_category.updated
     *
     * @mbggenerated
     */
    public Timestamp getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_content_category.updated
     *
     * @param updated the value for tb_content_category.updated
     *
     * @mbggenerated
     */
    public void setUpdated(Timestamp updated) {
        this.updated = updated;
    }
}